// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See rm_tb_top_routerlinkedlist.h for the primary calling header

#ifndef VERILATED_RM_TB_TOP_ROUTERLINKEDLIST___024ROOT_H_
#define VERILATED_RM_TB_TOP_ROUTERLINKEDLIST___024ROOT_H_  // guard

#include "verilated.h"

class rm_tb_top_routerlinkedlist__Syms;
class rm_tb_top_routerlinkedlist_Top_ModuleC0;
class rm_tb_top_routerlinkedlist_Top_ModuleC1;


class rm_tb_top_routerlinkedlist___024root final : public VerilatedModule {
  public:
    // CELLS
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1* __PVT__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__I1c1;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rst_ni;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edA__DOT__clk_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edA__DOT__rst_ni;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edB__DOT__clk_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edB__DOT__rst_ni;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edC__DOT__clk_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edC__DOT__rst_ni;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edD__DOT__clk_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edD__DOT__rst_ni;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edE__DOT__clk_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edE__DOT__rst_ni;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edF__DOT__clk_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edF__DOT__rst_ni;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT__clk_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT__rst_ni;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT__clk_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT__rst_ni;
        VL_IN8(rst_ni_tb,0,0);
        VL_IN8(signal_tb,7,0);
        VL_IN8(reset_lane_i_tb,7,0);
        VL_IN8(enque_ins_tb,0,0);
        VL_IN8(opcode_i_tb,6,0);
        VL_OUTW(lane_vector,111,0,4);
        VL_OUT8(lane_reset,6,0);
        VL_OUT8(itype,6,0);
        VL_OUT(lane0,20,0);
        VL_OUT(lane1,20,0);
        VL_OUT16(lane_mask,13,0);
        VL_OUT(parent_idx,20,0);
        VL_OUT8(has_parent,6,0);
        VL_OUT(child_idx,20,0);
        VL_OUT8(has_child,6,0);
        VL_OUT8(valid,6,0);
        VL_OUT8(list_reset_mask,6,0);
        VL_OUT8(monitor_ins,0,0);
        VL_OUT8(next_idx,2,0);
        CData/*7:0*/ rm_tb_top_routerlinkedlist__DOT__signal;
        CData/*7:0*/ rm_tb_top_routerlinkedlist__DOT__reset_lane_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__enque_ins;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__opcode_i;
        VlWide<4>/*111:0*/ rm_tb_top_routerlinkedlist__DOT____Vcellout__router__lane_vector_o;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__edA__DOT__lane_probe_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edA__DOT__probe_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edA__DOT__reset_o_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edA__DOT__reset_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edA__DOT____Vlvbound_h031c579d__0;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__edB__DOT__lane_probe_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edB__DOT__probe_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edB__DOT__reset_o_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edB__DOT____Vlvbound_h031c579d__0;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__edC__DOT__lane_probe_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edC__DOT__probe_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edC__DOT__reset_o_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edC__DOT__reset_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edC__DOT____Vlvbound_h031c579d__0;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__edD__DOT__lane_probe_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edD__DOT__probe_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edD__DOT__reset_o_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edD__DOT__reset_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edD__DOT____Vlvbound_h031c579d__0;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__edE__DOT__lane_probe_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edE__DOT__probe_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edE__DOT__reset_o_reg;
    };
    struct {
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edE__DOT____Vlvbound_h031c579d__0;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__edF__DOT__lane_probe_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edF__DOT__probe_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edF__DOT__reset_o_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edF__DOT____Vlvbound_h031c579d__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edF__DOT____VdfgTmp_hedd0e2b4__0;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT__lane_probe_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT__probe_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT__reset_o_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT__reset_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT__valid_leaf_event;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT____Vlvbound_h031c579d__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT____VdfgTmp_hedd0e2b4__0;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT__lane_probe_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT__probe_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT__reset_o_reg;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT__reset_val;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT__valid_leaf_event;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT____Vlvbound_h031c579d__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT____VdfgTmp_hedd0e2b4__0;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__lane_reset_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__flush_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__itype_o;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__monitor;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__lane0_o;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__lane_o_00;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__lane_o_01;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__has_01_lane;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__two_lane_o;
        SData/*13:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__alloc_mem;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__nxt_reset_lane;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__all_lanes_occupied;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_h6ca5d110__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_hfb11cf53__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_h77d24b89__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_h77d24b89__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_hfb11cf53__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_h064cc084__0;
        SData/*13:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__lane_reset_q;
        SData/*13:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__lane_reset_d;
        SData/*13:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__lane_mask_q;
        SData/*13:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__lane_mask_d;
        IData/*20:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__next_parent;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__queue_tail_q;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__queue_tail_d;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__queue_head;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__next_parent_valid;
        IData/*20:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__next_child;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__next_child_valid;
        CData/*6:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__reset_mask;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk2__DOT__unnamedblk3__DOT__c_parent;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk2__DOT__unnamedblk5__DOT__c_child;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h53f86517__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h10c7bce4__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h8d62c852__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h28f314e8__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h3455dccd__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hd007c83d__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hdf991483__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hd007c83d__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hc16e5030__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hdc3092a1__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h948239d2__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h529c8a97__0;
    };
    struct {
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h161306d5__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h86b51445__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h45218219__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h161306d5__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h388eb005__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h45218219__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hc16e5030__1;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hdc3092a1__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hc1424041__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h6c44a9e6__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h948239d2__1;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h529c8a97__1;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h45218219__2;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h549db542__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h944eea1e__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hb1225b1d__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h862e5f1c__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h85b9fd7b__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hb2025c4f__0;
        CData/*1:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hbff1194e__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hb1de1c7a__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hbbab519b__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h7cdb3fb6__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hcbc02661__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h8b5da8f0__0;
        CData/*1:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h47c8fadd__0;
        CData/*1:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h99dd1804__0;
        CData/*1:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hbff1194e__1;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h7cdb3fb6__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hbbab519b__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hb1de1c7a__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h5653da11__0;
        CData/*2:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h1a13cbf9__0;
        CData/*1:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h47c8fadd__1;
        CData/*1:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hbff1194e__2;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hb1de1c7a__2;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hbbab519b__2;
        CData/*1:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h47c8fadd__2;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h68026627__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h92d7c236__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_hc4bf4af7__0;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT____Vlvbound_h92d7c236__1;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT____Vcellinp__genblk1__BRA__0__KET____DOT__lane__lane_reset_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT____Vcellinp__genblk1__BRA__1__KET____DOT__lane__lane_reset_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT____Vcellinp__genblk1__BRA__2__KET____DOT__lane__lane_reset_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT____Vcellinp__genblk1__BRA__3__KET____DOT__lane__lane_reset_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT____Vcellinp__genblk1__BRA__4__KET____DOT__lane__lane_reset_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT____Vcellinp__genblk1__BRA__5__KET____DOT__lane__lane_reset_i;
        CData/*0:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT____Vcellinp__genblk1__BRA__6__KET____DOT__lane__lane_reset_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__c0_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__c1_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__c2_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__c3_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__c0_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__c1_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__c2_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__c3_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__c0_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__c1_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__c2_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__c3_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__c0_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__c1_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__c2_i;
    };
    struct {
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__c3_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__c0_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__c1_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__c2_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__c3_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__c0_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__c1_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__c2_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__c3_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__c0_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__c1_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__c2_i;
        CData/*3:0*/ rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__c3_i;
        CData/*1:0*/ __VdfgTmp_hd96324f3__0;
        CData/*1:0*/ __VdfgTmp_h3da4fa7d__0;
        CData/*0:0*/ __Vtrigrprev__TOP__clk_i;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__rst_ni;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edA__DOT__clk_i;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edA__DOT__rst_ni;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edB__DOT__clk_i;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edB__DOT__rst_ni;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edC__DOT__clk_i;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edC__DOT__rst_ni;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edD__DOT__clk_i;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edD__DOT__rst_ni;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edE__DOT__clk_i;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edE__DOT__rst_ni;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edF__DOT__clk_i;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edF__DOT__rst_ni;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edG__DOT__clk_i;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edG__DOT__rst_ni;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edH__DOT__clk_i;
        CData/*0:0*/ __Vtrigrprev__TOP__rm_tb_top_routerlinkedlist__DOT__edH__DOT__rst_ni;
        CData/*0:0*/ __VactContinue;
        VL_OUTW(monitor_o,69,0,3);
        VlWide<4>/*111:0*/ rm_tb_top_routerlinkedlist__DOT____Vcellinp__router__events_i;
        VL_OUT(num_events,31,0);
        VL_OUT(num_lanes,31,0);
        VL_OUT(num_rules,31,0);
        VL_OUT(test_type,31,0);
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edA__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edA__DOT__regval__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edB__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edB__DOT__regval__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edC__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edC__DOT__regval__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edD__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edD__DOT__regval__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edE__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edE__DOT__regval__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edF__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edF__DOT__regval__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edG__DOT__regval__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__edH__DOT__regval__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__tmp_cnt;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__set_alloc__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__set_alloc__DOT__unnamedblk5__DOT__i;
    };
    struct {
        VlWide<5>/*132:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__lane_mapping_q;
        VlWide<5>/*132:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__lane_mapping_d;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk2__DOT__unnamedblk3__DOT__unnamedblk4__DOT__j;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk2__DOT__unnamedblk5__DOT__unnamedblk6__DOT__j;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk9__DOT__i;
        IData/*31:0*/ rm_tb_top_routerlinkedlist__DOT__router__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(pc_i_tb,63,0);
        VlWide<29>/*903:0*/ rm_tb_top_routerlinkedlist__DOT__rm_cnt;
        VlWide<4>/*112:0*/ rm_tb_top_routerlinkedlist__DOT__rm_cnt_o;
        QData/*63:0*/ rm_tb_top_routerlinkedlist__DOT__pc_i;
        VlWide<4>/*112:0*/ rm_tb_top_routerlinkedlist__DOT____Vlvbound_hd7800ecb__0;
        VlWide<28>/*895:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT__pc_mem;
        QData/*63:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_h8e73882e__0;
        QData/*63:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_h580f53b7__0;
        QData/*63:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_h2d985dc2__0;
        QData/*63:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_h2d985dc2__1;
        QData/*63:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_h580f53b7__1;
        QData/*63:0*/ rm_tb_top_routerlinkedlist__DOT__rm_alloc__DOT____Vlvbound_hb3ac4d13__0;
        VlWide<29>/*903:0*/ __Vdly__rm_tb_top_routerlinkedlist__DOT__rm_cnt;
        VlUnpacked<CData/*0:0*/, 18> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<11> __VactTriggered;
    VlTriggerVec<11> __VnbaTriggered;

    // INTERNAL VARIABLES
    rm_tb_top_routerlinkedlist__Syms* const vlSymsp;

    // CONSTRUCTORS
    rm_tb_top_routerlinkedlist___024root(rm_tb_top_routerlinkedlist__Syms* symsp, const char* v__name);
    ~rm_tb_top_routerlinkedlist___024root();
    VL_UNCOPYABLE(rm_tb_top_routerlinkedlist___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
