// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_RM_TB_TOP_ROUTERLINKEDLIST__SYMS_H_
#define VERILATED_RM_TB_TOP_ROUTERLINKEDLIST__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "rm_tb_top_routerlinkedlist.h"

// INCLUDE MODULE CLASSES
#include "rm_tb_top_routerlinkedlist___024root.h"
#include "rm_tb_top_routerlinkedlist_Top_ModuleC0.h"
#include "rm_tb_top_routerlinkedlist_Top_ModuleC1.h"

// SYMS CLASS (contains all model state)
class rm_tb_top_routerlinkedlist__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    rm_tb_top_routerlinkedlist* const __Vm_modelp;
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    rm_tb_top_routerlinkedlist___024root TOP;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__0__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__1__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__2__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__3__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__4__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__5__KET____DOT__lane__DOT__I1c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__I0c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__I0c1;
    rm_tb_top_routerlinkedlist_Top_ModuleC0 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__I1c0;
    rm_tb_top_routerlinkedlist_Top_ModuleC1 TOP__rm_tb_top_routerlinkedlist__DOT__rm__DOT__genblk1__BRA__6__KET____DOT__lane__DOT__I1c1;

    // CONSTRUCTORS
    rm_tb_top_routerlinkedlist__Syms(VerilatedContext* contextp, const char* namep, rm_tb_top_routerlinkedlist* modelp);
    ~rm_tb_top_routerlinkedlist__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

#endif  // guard
